BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[SYF_USERMASTER] ALTER COLUMN [PASSWORD] NVARCHAR(128) NULL;
ALTER TABLE [dbo].[SYF_USERMASTER] ADD [SALT] NVARCHAR(128),
[emailVerificationToken] NVARCHAR(max),
[failedLoginAttempts] INT CONSTRAINT [SYF_USERMASTER_failedLoginAttempts_df] DEFAULT 0,
[lastFailedLogin] DATETIME2,
[lastLogin] DATETIME2,
[verificationExpires] DATETIME2;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
