let backendUrl = process.env.BACKEND_URL;

// let backendUrl = "https://syfnodejsprod-d7b9bsc4b7gwaeev.southindia-01.azurewebsites.net/api"; // Production

// let backendUrl = "https://finspeednodejs.azurewebsites.net/api"

async function getEndpoints() {
  let endpoints = {
    syncZbOrganization: `${backendUrl}/syncZbOrganization`,
    performanceTest: `${backendUrl}/performanceTest`,
    rcm_deleteData: `${backendUrl}/rcm_deleteData`,
    rcm_getData: `${backendUrl}/rcm_getData`,
    rcm_reportCreation: `${backendUrl}/rcm_reportCreation`,
    rcm_stateCodeDetails: `${backendUrl}/rcm_stateCodeDetails`,
    rcm_onloadData: `${backendUrl}/rcm_onloadData`,
    rcm_insertVendor: `${backendUrl}/rcm_insertVendor`,
    rcm_save: `${backendUrl}/rcm_save`,
    rcm_update: `${backendUrl}/rcm_update`,
    rcm_getUvData: `${backendUrl}/rcm_getUvData`,
    rcm_deleteDataLid: `${backendUrl}/rcm_deleteDataLid`,
    rcm_bulkreportCreation: `${backendUrl}/rcm_bulkreportCreation`,
    pm_getAssignmentNature: `${backendUrl}/pm_getAssignmentNature`,
    pm_getInvitedUserNames: `${backendUrl}/pm_getInvitedUserNames`,
    pm_getmilestones: `${backendUrl}/pm_getmilestones`,
    pm_delMilestones: `${backendUrl}/pm_delMilestones`,
    pm_milestoneBulkUpload: `${backendUrl}/pm_milestoneBulkUpload`,
    pm_getAssignmentNatureOptions: `${backendUrl}/pm_getAssignmentNatureOptions`,
    pm_milestoneUpdate: `${backendUrl}/pm_milestoneUpdate`,
    pm_getMilestoneUvData: `${backendUrl}/pm_getMilestoneUvData`,
    pm_saveMilestones: `${backendUrl}/pm_saveMilestones`,
    pm_delSingleMilestone: `${backendUrl}/pm_delSingleMilestone`,
    pm_getAssignmentData: `${backendUrl}/pm_getAssignmentData`,
    pm_getAssignmentLidName: `${backendUrl}/pm_getAssignmentLidName`,
    pm_deleteAssignment: `${backendUrl}/pm_deleteAssignment`,
    pm_assignmentBulkUpload: `${backendUrl}/pm_assignmentBulkUpload`,
    pm_getAssignmentUvData: `${backendUrl}/pm_getAssignmentUvData`,
    pm_displayTermsConditions: `${backendUrl}/pm_displayTermsConditions`,
    pm_getContractStatusQuery: `${backendUrl}/pm_getContractStatusQuery`,
    pm_insertTemplateTransaction: `${backendUrl}/pm_insertTemplateTransaction`,
    pm_updateProposalTemplateTransaction: `${backendUrl}/pm_updateProposalTemplateTransaction`,
    pm_getChatFromProposalTrans: `${backendUrl}/pm_getChatFromProposalTrans`,
    pm_updateChatProposal: `${backendUrl}/pm_updateChatProposal`,
    pm_updateProposalStatus: `${backendUrl}/pm_updateProposalStatus`,
    pm_getAssignmentNatureName: `${backendUrl}/pm_getAssignmentNatureName`,
    pm_getClientDetails: `${backendUrl}/pm_getClientDetails`,
    pm_getContractMasterDetails: `${backendUrl}/pm_getContractMasterDetails`,
    pm_checkEmailClients: `${backendUrl}/pm_checkEmailClients`,
    pm_getClientProjects: `${backendUrl}/pm_getClientProjects`,
    pm_getClientContract: `${backendUrl}/pm_getClientContract`,

    getProjectsWithContactInfo: `${backendUrl}/getProjectsWithContactInfo`,

    /////gstTracker
    gst_zohoNames: `${backendUrl}/gst_zohoNames`,
    gst_insertIntoGstNotices: `${backendUrl}/gst_insertIntoGstNotices`,
    gst_updateGstNotice: `${backendUrl}/gst_updateGstNotice`,

    gst_getNoticeTrackerData: `${backendUrl}/gst_getNoticeTrackerData`,
    gst_updateStatusNoticeTracker: `${backendUrl}/gst_updateStatusNoticeTracker`,

    gst_updateContractIdNoticeTracker: `${backendUrl}/gst_updateContractIdNoticeTracker`,
    gst_updateTimeExtensionFieldNoticeTracker: `${backendUrl}/gst_updateTimeExtensionFieldNoticeTracker`,

    //////
    pm_saveAssignment: `${backendUrl}/pm_saveAssignment`,
    pm_updateAssignment: `${backendUrl}/pm_updateAssignment`,
    pm_getLeadsData: `${backendUrl}/pm_getLeadsData`,
    pm_getCustomerData: `${backendUrl}/pm_getCustomerData`,
    pm_getVendorData: `${backendUrl}/pm_getVendorData`,
    pm_deleteLead: `${backendUrl}/pm_deleteLead`,
    pm_deleteContact: `${backendUrl}/pm_deleteContact`,
    pm_getLeads: `${backendUrl}/pm_getLeads`,
    pm_getContracts: `${backendUrl}/pm_getContracts`,
    pm_getProposals: `${backendUrl}/pm_getProposals`,
    pm_getOnloadDataLead: `${backendUrl}/pm_getOnloadDataLead`,
    pm_getUvDataLead: `${backendUrl}/pm_getUvDataLead`,
    pm_saveLead: `${backendUrl}/pm_saveLead`,
    pm_updateLead: `${backendUrl}/pm_updateLead`,
    pm_saveNewContact: `${backendUrl}/pm_saveNewContact`,
    pm_getUvDataClient: `${backendUrl}/pm_getUvDataClient`,
    pm_saveClient: `${backendUrl}/pm_saveClient`,
    pm_updateClient: `${backendUrl}/pm_updateClient`,
    pm_getAssignments: `${backendUrl}/pm_getAssignments`,
    pm_deleteAllProjects: `${backendUrl}/pm_deleteAllProjects`,
    pm_duplicateContract: `${backendUrl}/pm_duplicateContract`,
    pm_getContractData: `${backendUrl}/pm_getContractData`,
    pm_createContract: `${backendUrl}/pm_createContract`,
    pm_updateBlobUrl: `${backendUrl}/pm_updateBlobUrl`,
    pm_onloadDataContracts: `${backendUrl}/pm_onloadDataContracts`,
    pm_fetchContract: `${backendUrl}/pm_fetchContract`,
    pm_milestoneMaster: `${backendUrl}/pm_milestoneMaster`,
    pm_milestonesubForm: `${backendUrl}/pm_milestoneSubForm`,
    pm_saveContract: `${backendUrl}/pm_saveContract`,
    pm_deleteContractAssignment: `${backendUrl}/pm_deleteContractAssignment`,
    pm_deleteContractMilestone: `${backendUrl}/pm_deleteContractMilestone`,
    pm_getAllProjects: `${backendUrl}/pm_getAllProjects`,
    pm_getAllInvoices: `${backendUrl}/pm_getAllInvoices`,
    pm_updateInvoice: `${backendUrl}/pm_updateInvoice`,
    pm_pendingToSent: `${backendUrl}/pm_pendingToSent`,
    pm_getOngoingContractData: `${backendUrl}/pm_getOngoingContractData`,
    pm_saveClassification: `${backendUrl}/pm_saveClassification`,
    pm_showClassification: `${backendUrl}/pm_showClassification`,
    pm_deleteClassification: `${backendUrl}/pm_deleteClassification`,
    pm_showChecklist: `${backendUrl}/pm_showChecklist`,
    pm_deleteChecklist: `${backendUrl}/pm_deleteChecklist`,
    pm_fetchMilestones: `${backendUrl}/pm_fetchMilestones`,
    pm_fetchChecklist: `${backendUrl}/pm_fetchChecklist`,
    pm_saveChecklist: `${backendUrl}/pm_saveChecklist`,
    pm_getMaxContId: `${backendUrl}/pm_getMaxContId`,
    pm_getMaxAssignmentId: `${backendUrl}/pm_getMaxAssignmentId`,
    pm_getMaxMilestoneId: `${backendUrl}/pm_getMaxMilestoneId`,
    pm_updateContract: `${backendUrl}/pm_updateContract`,
    pm_getAllProjectData: `${backendUrl}/pm_getAllProjectData`,
    pm_updatePaidInvoice: `${backendUrl}/pm_updatePaidInvoice`,
    pm_updateSentInvoice: `${backendUrl}/pm_updateSentInvoice`,
    pm_reverseProject: `${backendUrl}/pm_reverseProject`,
    pm_onloadTemplate: `${backendUrl}/pm_onloadTemplate`,
    pm_fetchContractAssignmentNature: `${backendUrl}/pm_fetchContractAssignmentNature`,
    pm_fetchMilestoneSubform: `${backendUrl}/pm_fetchMilestoneSubform`,
    pm_getProjectData: `${backendUrl}/pm_getProjectData`,
    pm_getBillingAddress: `${backendUrl}/pm_getBillingAddress`,
    pm_getTotalAmount: `${backendUrl}/pm_getTotalAmount`,
    pm_timesheetAlert: `${backendUrl}/pm_timesheetAlert`,
    pm_changeAmount: `${backendUrl}/pm_changeAmount`,
    pm_obsDashboard_saveTasks: `${backendUrl}/pm_obsDashboard_saveTasks`,
    pm_obsDashboard_statusUpdate: `${backendUrl}/pm_obsDashboard_statusUpdate`,
    pm_obsDashboard_getTableDataPettyTask: `${backendUrl}/pm_obsDashboard_getTableDataPettyTask`,
    pm_obsDashboard_updatePettyTaskStatus: `${backendUrl}/pm_obsDashboard_updatePettyTaskStatus`,
    pm_obsDashboard_updatePettyTaskComment: `${backendUrl}/pm_obsDashboard_updatePettyTaskComment`,
    pm_obsDashboard_updateObservationremarks: `${backendUrl}/pm_obsDashboard_updateObservationremarks`,
    pm_obsDashboard_updateObservationComment: `${backendUrl}/pm_obsDashboard_updateObservationComment`,
    pm_obsDashboard_updateObservationStatus: `${backendUrl}/pm_obsDashboard_updateObservationStatus`,
    pm_obsDashboard_getProjectDataObservation: `${backendUrl}/pm_obsDashboard_getProjectDataObservation`,
    pm_obsDashboard_updateAllObservationObs: `${backendUrl}/pm_obsDashboard_updateAllObservationObs`,
    pm_obsDashboard_getMilestonesCount: `${backendUrl}/pm_obsDashboard_getMilestonesCount`,
    pm_obsDashboard_getProjectNames: `${backendUrl}/pm_obsDashboard_getProjectNames`,
    pm_obsDashboard_getPettyTaskUpdates: `${backendUrl}/pm_obsDashboard_getPettyTaskUpdates`,
    pm_totalUsersCount: `${backendUrl}/pm_totalUsersCount`,
    pm_cancelContracts: `${backendUrl}/pm_cancelContracts`,
    pm_cancelProjects: `${backendUrl}/pm_cancelProjects`,
    pm_statistics_getObservationType: `${backendUrl}/pm_statistics_getObservationType`,
    financial_showCommitment: `${backendUrl}/financial_showCommitment`,
    financial_delCommitment: `${backendUrl}/financial_delCommitment`,
    financial_fetchRawCoa: `${backendUrl}/financial_fetchRawCoa`,
    financial_saveCommitment: `${backendUrl}/financial_saveCommitment`,
    financial_updateCommitment: `${backendUrl}/financial_updateCommitment`,
    financial_getCommitment: `${backendUrl}/financial_getCommitment`,
    financial_getusernames: `${backendUrl}/financial_getusernames`,
    financial_ggshCoa: `${backendUrl}/financial_ggshCoa`,
    financial_tbTable: `${backendUrl}/financial_tbTable`,
    financial_saveMapping: `${backendUrl}/financial_saveMapping`,
    financial_updateMapping: `${backendUrl}/financial_updateMapping`,
    financial_coaExcelUpload: `${backendUrl}/financial_coaExcelUpload`,
    financial_coaLedgerData: `${backendUrl}/financial_coaLedgerData`,
    financial_getCoaOptions: `${backendUrl}/financial_getCoaOptions`,
    financial_fetchTemplate: `${backendUrl}/financial_fetchTemplate`,
    financial_insertTemplate: `${backendUrl}/financial_insertTemplate`,
    financial_updateTemplate: `${backendUrl}/financial_updateTemplate`,
    financial_balanceSheet: `${backendUrl}/financial_balanceSheet`,
    financial_updateCoaMapped: `${backendUrl}/financial_updateCoaMapped`,
    fetchCompanyGroup: `${backendUrl}/fetchCompanyGroup`,
    financial_misTable: `${backendUrl}/financial_misTable`,
    financial_voucherData: `${backendUrl}/financial_voucherData`,
    financial_pendingCoacount: `${backendUrl}/financial_pendingCoacount`,
    financial_coaView: `${backendUrl}/financial_coaView`,
    financial_createCoa: `${backendUrl}/financial_createCoa`,
    financial_deleteCoa: `${backendUrl}/financial_deleteCoa`,
    financial_updateCoaMaster: `${backendUrl}/financial_updateCoaMaster`,
    financial_updateCoaMasterSeq: `${backendUrl}/financial_updateCoaMasterSeq`,
    timesheet_getAllData: `${backendUrl}/timesheet_getAllData`,
    timesheet_delReportdata: `${backendUrl}/timesheet_delReportdata`,
    timesheet_getProjects: `${backendUrl}/timesheet_getProjects`,
    timesheet_getDetails: `${backendUrl}/timesheet_getDetails`,
    timesheet_getAllObservations: `${backendUrl}/timesheet_getAllObservations`,
    timesheet_getDayRecords: `${backendUrl}/timesheet_getDayRecords`,
    timesheet_choosenweek: `${backendUrl}/timesheet_choosenweek`,
    timesheet_getDepartment: `${backendUrl}/timesheet_getDepartment`,
    timesheet_saveData: `${backendUrl}/timesheet_saveData`,
    timesheet_updateData: `${backendUrl}/timesheet_updateData`,
    timesheet_saveDayReport: `${backendUrl}/timesheet_saveDayReport`,
    timesheet_fetchDayReportFilter: `${backendUrl}/timesheet_fetchDayReportFilter`,
    t2z_fetchCoaGroups: `${backendUrl}/t2z_fetchCoaGroups`,
    t2z_getDistinctOptions: `${backendUrl}/t2z_getDistinctOptions`,
    t2z_bulkUpdate: `${backendUrl}/t2z_bulkUpdate`,
    t2z_filterCoa: `${backendUrl}/t2z_filterCoa`,
    t2z_updateMutipleRow: `${backendUrl}/t2z_updateMutipleRow`,
    t2z_updateSingleRow: `${backendUrl}/t2z_updateSingleRow`,
    t2z_updateInputField: `${backendUrl}/t2z_updateInputField`,
    t2z_contacts: `${backendUrl}/t2z_contacts`,
    t2z_tableData: `${backendUrl}/t2z_tableData`,
    t2z_getMaxAmount: `${backendUrl}/t2z_getMaxAmount`,
    t2z_onloadDataTb: `${backendUrl}/t2z_onloadDataTb`,
    t2z_filterTb: `${backendUrl}/t2z_filterTb`,
    t2z_fetchToDate: `${backendUrl}/t2z_fetchToDate`,
    t2z_onloadvoucherType: `${backendUrl}/t2z_onloadvoucherType`,
    t2z_updateVoucher: `${backendUrl}/t2z_updateVoucher`,
    settings_getCompanies: `${backendUrl}/settings_getCompanies`,
    settings_addNew: `${backendUrl}/settings_addNew`,
    settings_updateGroup: `${backendUrl}/settings_updateGroup`,
    settings_updateCompany: `${backendUrl}/settings_updateCompany`,
    settings_updateGroupName: `${backendUrl}/settings_updateGroupName`,

    services_userAdd_GetExsistingUserList: `${backendUrl}/services_userAdd_GetExsistingUserList`,

    services_userAdd_addNewUser: `${backendUrl}/services_userAdd_addNewUser`,

    services_userAdd_addToPivot: `${backendUrl}/services_userAdd_addToPivot`,

    getProjectUsers_ua: `${backendUrl}/getProjectUsers_ua`,

    recordUserInvitation: `${backendUrl}/recordUserInvitation`,

    productvs: `${backendUrl}/productvs`,

    productdata: `${backendUrl}/productdata`,

    saveServiceOrder: `${backendUrl}/saveServiceOrder`,

    assignProductsToClient: `${backendUrl}/assignProductsToClient`,

    getProductsForClientAssignment: `${backendUrl}/getProductsForClientAssignment`,

    addProductToClient: `${backendUrl}/addProductToClient`,

    removeProductFromClient: `${backendUrl}/removeProductFromClient`,

    settings_displayRole: `${backendUrl}/settings_displayRole`,
    settings_saveRole: `${backendUrl}/settings_saveRole`,
    settings_updateRole: `${backendUrl}/settings_updateRole`,
    settings_displayAllRoles: `${backendUrl}/settings_displayAllRoles`,
    settings_deleteRoles: `${backendUrl}/settings_deleteRoles`,
    window_createAccount: `${backendUrl}/window_createAccount`,
    window_checkUser: `${backendUrl}/window_checkUser`,
    window_checkEmail: `${backendUrl}/window_checkEmail`,
    window_loginStatus: `${backendUrl}/window_loginStatus`,
    window_getInvites: `${backendUrl}/window_getInvites`,
    window_deleteAccess: `${backendUrl}/window_deleteAccess`,
    window_emailVerify: `${backendUrl}/window_emailVerify`,
    window_setExpiry: `${backendUrl}/window_setExpiry`,
    window_checkStatus: `${backendUrl}/window_checkStatus`,
    window_deleteVerifymail: `${backendUrl}/window_deleteVerifymail`,
    window_saveAccess: `${backendUrl}/window_saveAccess`,
    window_updateAccess: `${backendUrl}/window_updateAccess`,
    window_displayAccess: `${backendUrl}/window_displayAccess`,
    window_roleBasedModules: `${backendUrl}/window_roleBasedModules`,
    window_getInvitedUser: `${backendUrl}/window_getInvitedUser`,
    window_changePassword: `${backendUrl}/window_changePassword`,
    settings_updatetable: `${backendUrl}/settings_updatetable`,
    window_createAccountNew: `${backendUrl}/window_createAccountNew`,
    settings_getMyPlans: `${backendUrl}/settings_getMyPlans`,
    settings_updatePlan: `${backendUrl}/settings_updatePlan`,
    settings_getPlanOptions: `${backendUrl}/getPlanOptions`,
    settings_basicsFetch: `${backendUrl}/settings_basicsFetch`,
    settings_accountsFetch: `${backendUrl}/settings_accountsFetch`,
    settings_branchFetch: `${backendUrl}/settings_branchFetch`,
    settings_tanFetch: `${backendUrl}/settings_tanFetch`,
    settings_gstFetch: `${backendUrl}/settings_gstFetch`,
    settings_emptyValueInsert: `${backendUrl}/settings_emptyValueInsert`,
    settings_emptyValueInsertAcbk: `${backendUrl}/settings_emptyValueInsertAcbk`,
    settings_updateTable: `${backendUrl}/settings_updateTable`,
    settings_updateACBKTable: `${backendUrl}/settings_updateACBKTable`,
    settings_deleteRow: `${backendUrl}/settings_deleteRow`,
    settings_updateCompanyName: `${backendUrl}/settings_updateCompanyName`,
    window_changeSyncStatus: `${backendUrl}/window_changeSyncStatus`,
    financial_resetCompanyCoa: `${backendUrl}/financial_resetCompanyCoa`,
    config_setMainJson: `${backendUrl}/config_setMainJson`,
    config_fetchUserInfo: `${backendUrl}/config_fetchUserInfo`,
    config_sendMail: `${backendUrl}/config_sendMail`,
    config_getSchema: `${backendUrl}/config_getSchema`,
    config_getCompanyInfo: `${backendUrl}/config_getCompanyInfo`,
    config_getUserRoles: `${backendUrl}/config_getUserRoles`,
    config_getUserModules: `${backendUrl}/config_getUserModules`,
    config_getRoles: `${backendUrl}/config_getRoles`,
    config_getCountry: `${backendUrl}/config_getCountry`,
    config_getAcceptedInvites: `${backendUrl}/config_getAcceptedInvites`,
    config_changeInviteStatus: `${backendUrl}/config_changeInviteStatus`,
    config_bulkInsert: `${backendUrl}/config_bulkInsert`,
    reco_getAll: `${backendUrl}/reco_getAll`,
    reco_delete: `${backendUrl}/reco_delete`,
    reco_getData: `${backendUrl}/reco_getData`,
    reco_saveJson: `${backendUrl}/reco_saveJson`,
    reco_getTableData: `${backendUrl}/reco_getTableData`,
    reco_completeReco: `${backendUrl}/reco_completeReco`,
    reco_completeBulkReco: `${backendUrl}/reco_completeBulkReco`,
    reco_rejectReco: `${backendUrl}/reco_rejectReco`,
    reco_deleteTableData: `${backendUrl}/reco_deleteTableData`,
    reco_manualMatching: `${backendUrl}/reco_manualMatching`,
    financials_getSegments: `${backendUrl}/financials_getSegments`,
    financial_saveNewSegment: `${backendUrl}/financial_saveNewSegment`,
    financial_updateSegment: `${backendUrl}/financial_updateSegment`,
    settings_updateProfile: `${backendUrl}/settings_updateProfile`,
    admin_fetchModules: `${backendUrl}/admin_fetchModules`,
    admin_insertEmptyModule: `${backendUrl}/admin_insertEmptyModule`,
    admin_deleteModule: `${backendUrl}/admin_deleteModule`,
    admin_updateModule: `${backendUrl}/admin_updateModule`,
    admin_updateModuleSubCategory: `${backendUrl}/admin_updateModuleSubCategory`,
    admin_getAllModules: `${backendUrl}/admin_getAllModules`,
    admin_getAllPlans: `${backendUrl}/admin_getAllPlans`,
    admin_insertEmptyPlan: `${backendUrl}/admin_insertEmptyPlan`,
    admin_deletePlan: `${backendUrl}/admin_deletePlan`,
    admin_updatePlan: `${backendUrl}/admin_updatePlan`,
    sop_save: `${backendUrl}/sop_save`,
    sop_update: `${backendUrl}/sop_update`,
    sop_getData: `${backendUrl}/sop_getData`,
    sop_getAllData: `${backendUrl}/sop_getAllData`,
    sop_deleteData: `${backendUrl}/sop_deleteData`,
    sop_getById: `${backendUrl}/sop_getById`,
    speed_getGlobalReport: `${backendUrl}/speed_getGlobalReport`,
    speed_getLidGlobalReport: `${backendUrl}/speed_getLidGlobalReport`,
    speed_getGlobalTemplate: `${backendUrl}/speed_getGlobalTemplate`,
    speed_getTemplateTransaction: `${backendUrl}/speed_getTemplateTransaction`,
    speed_getTransactionCompany: `${backendUrl}/speed_getTransactionCompany`,
    speed_getSpeedFileDrive: `${backendUrl}/speed_getSpeedFileDrive`,
    speed_getSpeedFileDriveDataCompany: `${backendUrl}/speed_getSpeedFileDriveDataCompany`,
    speed_getSpeedDriveData: `${backendUrl}/speed_getSpeedDriveData`,
    speed_checkfileRecord: `${backendUrl}/speed_checkfileRecord`,
    speed_insertFileRecord: `${backendUrl}/speed_insertFileRecord`,
    speed_insertRoleFileRecord: `${backendUrl}/speed_insertRoleFileRecord`,
    speed_updateFileRecord: `${backendUrl}/speed_updateFileRecord`,
    speed_financialYearOnly: `${backendUrl}/speed_financialYearOnly`,
    speed_getProjects_clientname: `${backendUrl}/speed_getProjects_clientname`,
    speed_getMonth: `${backendUrl}/speed_getMonth`,
    speed_getGroupClientContact: `${backendUrl}/speed_getGroupClientContact`,
    speed_getAllContracts: `${backendUrl}/speed_getAllContracts`,
    speed_getMatchingClientName: `${backendUrl}/speed_getMatchingClientName`,
    document_getTransactionCompanyMaster: `${backendUrl}/document_getTransactionCompanyMaster`,
    document_getPathtransactionReportMaster: `${backendUrl}/document_getPathtransactionReportMaster`,
    document_getPathtemplateTransaction: `${backendUrl}/document_getPathtemplateTransaction`,
    document_getGlobalId: `${backendUrl}/document_getGlobalId`,
    document_getTransactionId: `${backendUrl}/document_getTransactionId`,
    document_updateGlobalMaster: `${backendUrl}/document_updateGlobalMaster`,
    document_insertGlobalMaster: `${backendUrl}/document_insertGlobalMaster`,
    document_updateTransactionMaster: `${backendUrl}/document_updateTransactionMaster`,
    document_insertTransactionMaster: `${backendUrl}/document_insertTransactionMaster`,
    pm_obsDashboard: `${backendUrl}/pm_obsDashboard`,
    pm_obsDashboard_markProjectCompletion: `${backendUrl}/pm_obsDashboard_markProjectCompletion`,
    pm_obsDashboard_getmilestones: `${backendUrl}/pm_obsDashboard_getmilestones`,
    pm_obsDashboard_updateMilestone: `${backendUrl}/pm_obsDashboard_updateMilestone`,
    pm_obsDashboard_addNewTask: `${backendUrl}/pm_obsDashboard_addNewTask`,
    pm_obsDashboard_updatePersonResponsible: `${backendUrl}/pm_obsDashboard_updatePersonResponsible`,
    pm_obsDashboard_deleteTasks: `${backendUrl}/pm_obsDashboard_deleteTasks`,
    pm_obsDashboard_update: `${backendUrl}/pm_obsDashboard_update`,
    pm_obsDashboard_getTeamProgress: `${backendUrl}/pm_obsDashboard_getTeamProgress`,
    templates_onloadData: `${backendUrl}/templates_onloadData`,
    templates_getTabCounts: `${backendUrl}/templates_getTabCounts`,
    templates_getTableData: `${backendUrl}/templates_getTableData`,
    templates_updateStage: `${backendUrl}/templates_updateStage`,
    templates_updateInputs: `${backendUrl}/templates_updateInputs`,
    forms_fetchOption: `${backendUrl}/forms_fetchOption`,
    forms_saveData: `${backendUrl}/forms_saveData`,
    forms_getuvData: `${backendUrl}/forms_getuvData`,
    forms_updateData: `${backendUrl}/forms_updateData`,
    forms_saveSubform: `${backendUrl}/forms_saveSubform`,
    forms_getUvSubFormData: `${backendUrl}/forms_getUvSubFormData`,
    forms_getEmployeeList: `${backendUrl}/forms_getEmployeeList`,
    forms_deleteRowData: `${backendUrl}/forms_deleteRowData`,

    getEmployeeTimesheetOptions: `${backendUrl}/getEmployeeTimesheetOptions`,

    myspace_getKpiMaster: `${backendUrl}/myspace_getKpiMaster`,
    myspace_insertKpiMaster: `${backendUrl}/myspace_insertKpiMaster`,
    myspace_deleteKpiMaster: `${backendUrl}/myspace_deleteKpiMaster`,
    config_workpaper: `${backendUrl}/config_workpaper`,
    myspace_updateKpiMaster: `${backendUrl}/myspace_updateKpiMaster`,
    getDropdownData: `${backendUrl}/getDropdownData`,
    master_deleteDropdown: `${backendUrl}/master_deleteDropdown`,
    master_updateDropdown: `${backendUrl}/master_updateDropdown`,
    master_getAllDropdownNames: `${backendUrl}/master_getAllDropdownNames`,
    master_viewDropdown: `${backendUrl}/master_viewDropdown`,
    master_saveDropdown: `${backendUrl}/master_saveDropdown`,
    pm_changeStatus: `${backendUrl}/pm_changeStatus`,
    pm_updateOngoing: `${backendUrl}/pm_updateOngoing`,
    pm_getAssigmentCriteria: `${backendUrl}/pm_getAssigmentCriteria`,
    pm_addAssignmentService: `${backendUrl}/pm_addAssignmentService`,
    pm_updateAssignmentService: `${backendUrl}/pm_updateAssignmentService`,
    pm_deleteCritDoc: `${backendUrl}/pm_deleteCritDoc`,
    pm_deleteAssignmentCriteria: `${backendUrl}/pm_deleteAssignmentCriteria`,
    extDocs_getBalance: `${backendUrl}/extDocs_getBalance`,
    extDocs_getTableData: `${backendUrl}/extDocs_getTableData`,
    extDocs_checkData: `${backendUrl}/extDocs_checkData`,
    extDocs_deleteExtData: `${backendUrl}/extDocs_deleteExtData`,
    extDocs_deleteBatch: `${backendUrl}/extDocs_deleteBatch`,
    extDocs_getPartyNames: `${backendUrl}/extDocs_getPartyNames`,
    extDocs_updateTag: `${backendUrl}/extDocs_updateTag`,
    extDocs_manageData: `${backendUrl}/extDocs_manageData`,
    extDocs_insertExtData: `${backendUrl}/extDocs_insertExtData`,
    extDocs_updateExtData: `${backendUrl}/extDocs_updateExtData`,
    recoBots_getAllReco: `${backendUrl}/recoBots_getAllReco`,
    extDocs_getContactsPartyNames: `${backendUrl}/extDocs_getContactsPartyNames`,
    extDocs_deleteData: `${backendUrl}/extDocs_deleteData`,
    extDocs_getCoaOptionsDocs: `${backendUrl}/extDocs_getCoaOptionsDocs`,
    extDocs_insertExtTab: `${backendUrl}/extDocs_insertExtTab`,
    extDocs_updateExtTab: `${backendUrl}/extDocs_updateExtTab`,
    extDocs_viewExtTab: `${backendUrl}/extDocs_viewExtTab`,
    extDocs_getMasterExtTabs: `${backendUrl}/extDocs_getMasterExtTabs`,
    extDocs_getExtTabsData: `${backendUrl}/extDocs_getExtTabsData`,
    extDocs_deleteExtTabsData: `${backendUrl}/extDocs_deleteExtTabsData`,
    extDocs_getAllExtTabs: `${backendUrl}/extDocs_getAllExtTabs`,
    records_getRecordsData: `${backendUrl}/records_getRecordsData`,
    records_getAllRecords: `${backendUrl}/records_getAllRecords`,
    records_deleteRecords: `${backendUrl}/records_deleteRecords`,
    reco_getSummary: `${backendUrl}/reco_getSummary`,
    reco_saveSummary: `${backendUrl}/reco_saveSummary`,

    //////////services_userList.js
    services_userList_zohoData: `${backendUrl}/services_userList_zohoData`,
    services_userList_zohocontact: `${backendUrl}/services_userList_zohocontact`,

    services_userList_getExistingPortalClients: `${backendUrl}/services_userList_getExistingPortalClients`,

    //////////
    records_addRecords: `${backendUrl}/records_addRecords`,
    records_getRecordData: `${backendUrl}/records_getRecordData`,
    records_getRecordsGroupBy: `${backendUrl}/records_getRecordsGroupBy`,
    reco_removeLineItem: `${backendUrl}/reco_removeLineItem`,
    gst_getGstin: `${backendUrl}/gst_getGstin`,
    gst_getGstr2bData: `${backendUrl}/gst_getGstr2bData`,
    // jobcard
    jobcard_getProjectDataObservation: `${backendUrl}/jobcard_getProjectDataObservation`,
    jobcard_fetchProjects: `${backendUrl}/jobcard_fetchProjects`,
    // projectdesk
    projectdesk_getObservstionDetail: `${backendUrl}/projectdesk_getObservstionDetail`,
    projectdesk_getMilestoneDetails: `${backendUrl}/projectdesk_getMilestoneDetails`,
    projectdesk_getChecklistDetails: `${backendUrl}/projectdesk_getChecklistDetails`,

    sanjay_getAssignedPortalUsers: `${backendUrl}/sanjay_getAssignedPortalUsers`,

    projectdesk_getTeamMembersDetails: `${backendUrl}/projectdesk_getTeamMembersDetails`,
    projectdesk_getTimeSheetDetails: `${backendUrl}/projectdesk_getTimeSheetDetails`,
    projectdesk_getDocumentDetails: `${backendUrl}/projectdesk_getDocumentDetails`,
    projectdesk_saveBlobUrl: `${backendUrl}/projectdesk_saveBlobUrl`,
    projectdesk_exportBlobUrl: `${backendUrl}/projectdesk_exportBlobUrl`,
    projectdesk_saveKycBlobUrl: `${backendUrl}/projectdesk_saveKycBlobUrl`,
    projectdesk_getkycBlobUrl: `${backendUrl}/projectdesk_getkycBlobUrl`,
    projectdesk_getstoredBlobUrl: `${backendUrl}/projectdesk_getstoredBlobUrl`,
    projectdesk_deleteBlobUrl: `${backendUrl}/projectdesk_deleteBlobUrl`,

    pm_getPendingLeads: `${backendUrl}/pm_getPendingLeads`,
    contractStatusChange: `${backendUrl}/contractStatusChange`,
    obs_getPreSalesValidationData: `${backendUrl}/obs_getPreSalesValidationData`,
    obs_saveMilestonePsvalidation: `${backendUrl}/obs_saveMilestonePsvalidation`,
    obs_PSsalesAllcontractsstatusChange: `${backendUrl}/obs_PSsalesAllcontractsstatusChange`,
//////july 9 added by sanjay
    completeObservationWithRemarks: `${backendUrl}/completeObservationWithRemarks`,

    getProjectDataObservationNew : `${backendUrl}/getProjectDataObservationNew`,

    
       updateAllObservationObsNew  : `${backendUrl}/updateAllObservationObsNew`,



       addObservationEntry : `${backendUrl}/addObservationEntry`,

////////////////////////////
//////////////////////itreturnfilling surmmary //////////

   fetchItReturns : `${backendUrl}/fetchItReturns`,


////////////////////////end//////////////////////////////
    // portal service
    portal_getServices: `${backendUrl}/portal_getServices`,

    portal_getServiceCriteriaPayment: `${backendUrl}/portal_getServiceCriteriaPayment`,

    portal_getZohoClientName: `${backendUrl}/portal_getZohoClientName`,

    removeServiceOrder: `${backendUrl}/removeServiceOrder`,

    addServiceOrder: `${backendUrl}/addServiceOrder`,

    getServiceOrdersForClient: `${backendUrl}/getServiceOrdersForClient`,
    portal_paymentCreation: `${backendUrl}/portal_paymentCreation`,
    speed_getPersonalDocuments: `${backendUrl}/speed_getPersonalDocuments`,
    pm_saveProposal: `${backendUrl}/pm_saveProposal`,
  };
  let result = Buffer.from(JSON.stringify(endpoints)).toString("base64");
  return result;
}

module.exports = { getEndpoints };
